# Generated by Django 4.2.6 on 2023-11-18 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=250, verbose_name='slug')),
                ('content', models.TextField(blank=True, null=True, verbose_name='содержимое')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение (превью)')),
                ('data_create', models.DateTimeField(default=datetime.datetime(2023, 11, 18, 22, 38, 39, 688518), verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('view_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
