# Generated by Django 4.2.6 on 2023-12-06 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 19, 32, 4, 585199), verbose_name='дата создания'),
        ),
    ]
