# Generated by Django 4.2.6 on 2023-12-13 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_data_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 19, 23, 31, 336612), verbose_name='дата создания'),
        ),
    ]
