# Generated by Django 4.2.6 on 2024-01-03 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_data_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 20, 34, 46, 283432), verbose_name='дата создания'),
        ),
    ]
